[package]
name = "stress2"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]
publish = false

[profile.release]
debug = true

[features]
default = ["async_snapshots"]
async_snapshots = ["sled/async_snapshots"]
lock_free_delays = ["sled/lock_free_delays"]
check_snapshot_integrity = ["sled/check_snapshot_integrity"]
compression = ["sled/compression"]
no_logs = ["sled/no_logs"]
no_metrics = ["sled/no_metrics"]
measure_allocs = ["sled/measure_allocs"]
no_jemalloc = []

[dependencies]
serde = "1.0"
serde_derive = "1.0"
docopt = "1.0"
env_logger = "0.5"
rand = "0.4"
sled = { path = "../../crates/sled" }
