[workspace]
members = [
  "crates/pagecache",
  "crates/pagetable",
  "crates/sled",
  "crates/tx",
  "tests",
]
exclude = [
  "benchmarks/stress2",
  "bindings/sled-native",
  "crates/deterministic",
  "crates/model",
  "crates/simulator",
  "examples/crdt_merge_store",
  "examples/pessimistic_transactions",
  "examples/playground",
]

[profile.release]
debug = 2

[profile.dev]
opt-level = 0
